[workspace]
members = [ 
    # "bin/bootstrap-arbitrum-discovery", 
    "bin/bot", 
    "bin/playground", 
    "crates/blockchain",
    "crates/defi/erc20", "crates/defi/protocols/pancakeswap", 
    "crates/defi/protocols/protocol", 
    "crates/defi/protocols/uniswap", 
    "crates/evm/evm", 
    "crates/evm/evm-core", 
    "crates/evm/evm-procmacro", "crates/monitoring", 
    "crates/storage",
    "crates/token-graph"
]

resolver = "2"

[workspace.dependencies]
plutus-blockchain = { path = "crates/blockchain" }

plutus-defi-erc20 = { path = "crates/defi/erc20" }
plutus-defi-protocols-protocol = { path = "crates/defi/protocols/protocol" }
plutus-defi-protocols-uniswap = { path = "crates/defi/protocols/uniswap" }
plutus-defi-protocols-pancakeswap = { path = "crates/defi/protocols/pancakeswap" }

plutus-evm = { path = "crates/evm/evm" }
plutus-evm-core = { path = "crates/evm/evm-core" }
plutus-evm-procmacro = { path = "crates/evm/evm-procmacro" }

plutus-storage = { path = "crates/storage" }

plutus-token-graph = { path = "crates/token-graph" }

plutus-monitoring = { path = "crates/monitoring" }

futures = "0.3.31"
petgraph = "0.7.1"
alloy = "0.9.2"
anyhow = "1.0.95"
dotenvy_macro = "0.15.7"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
sqlx = "0.8.3"
hashbrown = "0.15.2"
thiserror = "2.0.11"
lazy_static = "1.5.0"
derive_more = "2.0.1"
async-trait = "0.1.86"
uniswap_v3_math = "0.5.3"
strum = "0.27.0"
dyn-clone = "1.0.18"
hex = "0.4.3"
rayon = "1.10.0"

proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.98"

revm = { git = "https://github.com/bluealloy/revm/" }
revm-database = { git = "https://github.com/bluealloy/revm/" }
