[package]
name = "plutus-defi-protocols-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
plutus-storage.workspace = true
plutus-evm.workspace = true

alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
derive_more.workspace = true
hashbrown.workspace = true
tokio.workspace = true
