[package]
name = "plutus-evm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
revm = { workspace = true, features = ["hashbrown", "optional_balance_check"] }
revm-database = { workspace = true, features = ["alloydb"] }
alloy.workspace = true

thiserror.workspace = true
anyhow.workspace = true
derive_more = { workspace = true, features = ["full"] }
hashbrown.workspace = true
parking_lot.workspace = true
tracing.workspace = true
futures.workspace = true
