[package]
name = "plutus-token-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
plutus-defi-erc20.workspace = true
plutus-evm.workspace = true
plutus-defi-protocols-protocol.workspace = true
plutus-defi-price-oracle.workspace = true

tokio.workspace = true
petgraph.workspace = true
anyhow.workspace = true
hashbrown.workspace = true
tracing.workspace = true
futures.workspace = true
rayon.workspace = true
fxhash = "0.2.1"

[dev-dependencies]
criterion.workspace = true
plutus-storage.workspace = true
alloy.workspace = true
dotenvy_macro.workspace = true
plutus-defi-protocols-uniswap.workspace = true

[[bench]]
name = "opportunities"
harness = false
